### ISSUE TITLE
getStatus returns false even if server responds correctly

### ISSUE THREAD

**Issue by haltuf** [VitexSoftware/PHP-Pohoda-Connector#2]
Hi, not sure if not my fault somehow, but [this line](https://github.com/VitexSoftware/PHP-Pohoda-Connector/blob/main/src/mServer/Client.php#L451) seems to cause the following problem:

When calling
```
print_r($client->getStatus());
```
it returns false even if the server is up.

The reason is that `$lastCurlResponse` is 
```
string(215) "<?xml version="1.0" encoding="UTF-8"?>
<mServer><message>Response from POHODA mServer</message><name>mServer1</name><se                                                                         rver>http://IMAGINEO-2:7777</server><status>idle</status><processing>0</processi                                                                         ng></mServer>"
```

and the second condition fails.

Personally, I fixed it with:

```
return ($this->doCurlRequest($this->url . '/status','POST') === 200) && str_contains($this->lastCurlResponse, 'Response from POHODA mServer');
```

**Comment by Vitexus** [comment]
Thank you, for your contribution.
It will published as part of next release
